service: cloud-highway-one-api

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  logs:
    restApi: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: 'arn:aws:dynamodb:us-west-2:*:table/CloudHighwayOne'

functions:
  GetInterRegionalLatency:
    handler: api.interRegionalLatency
    timeout: 10
    events:
      - http:
          path: getLatency
          method: get
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*"statusCode":400,.*'
            500:
              pattern: '.*"statusCode":500,.*'
