service: cloud-highway-one-aws

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
      Resource: 'arn:aws:dynamodb:us-west-2:*:table/CloudHighwayOne'

functions:
  PingAllRegions:
    handler: ping.ping
    events:
      - schedule: rate(30 minutes)
