name: Deployment

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '12.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install AWS Project Dependencies
        working-directory: ./cloud-highway-one-aws
        run: yarn install
      - name: Deploy to AWS us-west-2
        run: serverless deploy --region us-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
