name: API Deployment (DEV)

on:
  push:
    branches: [deploy/api/dev/*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: "12.x"
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install Dependencies
        working-directory: ./cloud-highway-one-api
        run: yarn install
      - name: Deploy to AWS us-west-2
        working-directory: ./cloud-highway-one-api
        run: serverless deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RAPID_API_SECRET_KEY: ${{ secrets.RAPID_API_SECRET_KEY_DEV }}
