name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint cloud-highway-one-api
        working-directory: ./cloud-highway-one-api
        run: |
          yarn install
          yarn lint
      - name: eslint cloud-highway-one-aws
        working-directory: ./cloud-highway-one-aws
        run: |
          yarn install
          yarn lint
